language:
  node_js
install:
  - npm i
  - npm i -g codecov
node_js:
#  - '4' # removed since nyc code requires ES6 syntax support, node.js 4 fails on this
  - '6'
  - '8'
  - '10'
  - '12'
after_success:
  - npm run report-coverage
